practice_act(
    be_present(
        connect_with_present_moment,
        connect_with_knowing_self
    ),
    open_up(
        accept,
        defuse
    ),
    do_what_matters(
        identify_values,
        take_committed_action
    )
).
