go :- generate_html_file('manual_output.html').

generate_html_file(FileName) :-
    open(FileName, write, Stream, [encoding(utf8)]),
    html(Stream),
    close(Stream).

html(S) :-
    write(S, '<!DOCTYPE html>\n'),
    write(S, '<html>\n'),
    head(S),
    body(S),
    write(S, '</html>\n').

head(S) :-
    write(S, '<head>\n'),
    title(S),
    style(S),
    write(S, '</head>\n').

title(S) :-
    write(S, '<title>My Manual HTML Page</title>\n').

style(S) :-
    write(S, '<style>\n'),
    write(S, '  body { font-family: sans-serif; }\n'),
    write(S, '</style>\n').

body(S) :-
    write(S, '<body>\n'),
    write(S, '<h1>Hello from Prolog!</h1>\n'),
    write(S, '<p>This page was generated by hand-written Prolog code.</p>\n'),
    write(S, '</body>\n').
