% orientation_report.pl
:- use_module(library(date)).

:- dynamic cell/3.

canvas(rows, 48).
canvas(columns, 104).

rows(R) :- 
    canvas(rows, R).

columns(C) :- 
    canvas(columns, C).

bottom_row(R) :- 
    canvas(rows, R).

% Get current timestamp as an atom, formatted to the second
timestamp(Text) :-
    get_time(Time),
    format_time(atom(Text), '%Y-%m-%d %H:%M:%S', Time).

% Clear canvas memory before writing
clear_canvas :-
    retractall(cell(_, _, _)).

% Place text at a specific Row and Starting Column
% Default: left justification
place_text(Row, Col, Text) :-
    place_text(Row, Col, Text, left_justified).

% Justified placement
place_text(Row, Col, Text, left_justified) :-
    place_text_direct(Row, Col, Text).

place_text(Row, Col, Text, right_justified) :-
    atom_length(Text, Len),
    StartCol is Col - Len + 1,
    place_text_direct(Row, StartCol, Text).

place_text(Row, Col, Text, center_justified) :-
    atom_length(Text, Len),
    HalfLen is Len // 2,
    StartCol is Col - HalfLen,
    place_text_direct(Row, StartCol, Text).

% Core placement logic (no justification logic here)
place_text_direct(Row, Col, Text) :-
    atom_chars(Text, Chars),
    place_chars(Row, Col, Chars).

place_chars(_, _, []) :- !.
place_chars(Row, Col, [Char|Rest]) :-
    assertz(cell(Row, Col, Char)),
    Col1 is Col + 1,
    place_chars(Row, Col1, Rest).

% Place on page predicates
place_on_page(Row, Text, left_justified) :-
    place_text(Row, 1, Text, left_justified).

place_on_page(Row, Text, right_justified) :-
    columns(C),
    atom_length(Text, Len),
    StartCol is C - Len + 1,
    place_text(Row, StartCol, Text, left_justified).

place_on_page(Row, Text, center_justified) :-
    columns(C),
    atom_length(Text, Len),
    StartCol is ((C - Len) // 2) + 1,
    place_text(Row, StartCol, Text, left_justified).

% Shortcuts for placing on a line
center_text(Row, Text) :-
    place_on_page(Row, Text, center_justified).

left_text(Row, Text) :-
    place_on_page(Row, Text, left_justified).

right_text(Row, Text) :-
    place_on_page(Row, Text, right_justified).

% Build the page content before writing
build_page :-
    clear_canvas,
    center_text(1, 'That Piano Entertainment, LLC'),
    left_text(1, 'Weekly Orientation Report'),
    right_text(1, 'June 8 - June 11, 2025'),
    bottom_row(BRow),
    right_text(BRow, 'Generated by Prolog orientation_report.pl'),
    timestamp(Stamp), left_text(BRow, Stamp).

% Write the canvas to a file
write_canvas(File) :-
    build_page,
    rows(R),
    columns(C),
    open(File, write, Stream),
    write_canvas_rows(1, R, C, Stream),
    close(Stream).

write_canvas_rows(Row, MaxRow, _, _) :-
    Row > MaxRow, !.
write_canvas_rows(Row, MaxRow, MaxCol, Stream) :-
    write_canvas_row(Row, 1, MaxCol, Stream),
    nl(Stream),
    Row1 is Row + 1,
    write_canvas_rows(Row1, MaxRow, MaxCol, Stream).

write_canvas_row(_, Col, MaxCol, _) :-
    Col > MaxCol, !.
write_canvas_row(Row, Col, MaxCol, Stream) :-
    ( cell(Row, Col, Char) -> true ; Char = '.' ),
    put_char(Stream, Char),
    Col1 is Col + 1,
    write_canvas_row(Row, Col1, MaxCol, Stream).

write_canvas :- 
    write_canvas("orientation_report.txt").